package com.example.order.entity;

import java.io.Serializable;
import java.util.Date;

public class GSysOrderProgress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order_progress.PROGRESS_ID
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    private Long progressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order_progress.ORDER_ID
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order_progress.CREAT_TIME
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order_progress.STATUS
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order_progress.PROGRESS_ID
     *
     * @return the value of g_sys_order_progress.PROGRESS_ID
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    public Long getProgressId() {
        return progressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order_progress.PROGRESS_ID
     *
     * @param progressId the value for g_sys_order_progress.PROGRESS_ID
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    public void setProgressId(Long progressId) {
        this.progressId = progressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order_progress.ORDER_ID
     *
     * @return the value of g_sys_order_progress.ORDER_ID
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order_progress.ORDER_ID
     *
     * @param orderId the value for g_sys_order_progress.ORDER_ID
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order_progress.CREAT_TIME
     *
     * @return the value of g_sys_order_progress.CREAT_TIME
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order_progress.CREAT_TIME
     *
     * @param creatTime the value for g_sys_order_progress.CREAT_TIME
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order_progress.STATUS
     *
     * @return the value of g_sys_order_progress.STATUS
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order_progress.STATUS
     *
     * @param status the value for g_sys_order_progress.STATUS
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", progressId=").append(progressId);
        sb.append(", orderId=").append(orderId);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GSysOrderProgress other = (GSysOrderProgress) that;
        return (this.getProgressId() == null ? other.getProgressId() == null : this.getProgressId().equals(other.getProgressId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getCreatTime() == null ? other.getCreatTime() == null : this.getCreatTime().equals(other.getCreatTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProgressId() == null) ? 0 : getProgressId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getCreatTime() == null) ? 0 : getCreatTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }
}