package com.example.order.entity;

import java.io.Serializable;
import java.util.Date;

public class GSysAnnouncementManagement implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.ANNOUNCEMENT_ID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private Long announcementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.USER_ID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.ANNOUNCEMENT
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private String announcement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.REMARK
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.ANNOUNCEMENT_URL
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private String announcementUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.CREATTIME
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.RELEASETIME
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private Date releasetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.SORT
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private Long sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.RELEASE_STATUS
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private String releaseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_announcement_management.IS_VALID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.ANNOUNCEMENT_ID
     *
     * @return the value of g_sys_announcement_management.ANNOUNCEMENT_ID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public Long getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.ANNOUNCEMENT_ID
     *
     * @param announcementId the value for g_sys_announcement_management.ANNOUNCEMENT_ID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setAnnouncementId(Long announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.USER_ID
     *
     * @return the value of g_sys_announcement_management.USER_ID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.USER_ID
     *
     * @param userId the value for g_sys_announcement_management.USER_ID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.ANNOUNCEMENT
     *
     * @return the value of g_sys_announcement_management.ANNOUNCEMENT
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public String getAnnouncement() {
        return announcement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.ANNOUNCEMENT
     *
     * @param announcement the value for g_sys_announcement_management.ANNOUNCEMENT
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setAnnouncement(String announcement) {
        this.announcement = announcement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.REMARK
     *
     * @return the value of g_sys_announcement_management.REMARK
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.REMARK
     *
     * @param remark the value for g_sys_announcement_management.REMARK
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.ANNOUNCEMENT_URL
     *
     * @return the value of g_sys_announcement_management.ANNOUNCEMENT_URL
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public String getAnnouncementUrl() {
        return announcementUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.ANNOUNCEMENT_URL
     *
     * @param announcementUrl the value for g_sys_announcement_management.ANNOUNCEMENT_URL
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setAnnouncementUrl(String announcementUrl) {
        this.announcementUrl = announcementUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.CREATTIME
     *
     * @return the value of g_sys_announcement_management.CREATTIME
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.CREATTIME
     *
     * @param creattime the value for g_sys_announcement_management.CREATTIME
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.RELEASETIME
     *
     * @return the value of g_sys_announcement_management.RELEASETIME
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public Date getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.RELEASETIME
     *
     * @param releasetime the value for g_sys_announcement_management.RELEASETIME
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.SORT
     *
     * @return the value of g_sys_announcement_management.SORT
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.SORT
     *
     * @param sort the value for g_sys_announcement_management.SORT
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.RELEASE_STATUS
     *
     * @return the value of g_sys_announcement_management.RELEASE_STATUS
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public String getReleaseStatus() {
        return releaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.RELEASE_STATUS
     *
     * @param releaseStatus the value for g_sys_announcement_management.RELEASE_STATUS
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setReleaseStatus(String releaseStatus) {
        this.releaseStatus = releaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_announcement_management.IS_VALID
     *
     * @return the value of g_sys_announcement_management.IS_VALID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_announcement_management.IS_VALID
     *
     * @param isValid the value for g_sys_announcement_management.IS_VALID
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", announcementId=").append(announcementId);
        sb.append(", userId=").append(userId);
        sb.append(", announcement=").append(announcement);
        sb.append(", remark=").append(remark);
        sb.append(", announcementUrl=").append(announcementUrl);
        sb.append(", creattime=").append(creattime);
        sb.append(", releasetime=").append(releasetime);
        sb.append(", sort=").append(sort);
        sb.append(", releaseStatus=").append(releaseStatus);
        sb.append(", isValid=").append(isValid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GSysAnnouncementManagement other = (GSysAnnouncementManagement) that;
        return (this.getAnnouncementId() == null ? other.getAnnouncementId() == null : this.getAnnouncementId().equals(other.getAnnouncementId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAnnouncement() == null ? other.getAnnouncement() == null : this.getAnnouncement().equals(other.getAnnouncement()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getAnnouncementUrl() == null ? other.getAnnouncementUrl() == null : this.getAnnouncementUrl().equals(other.getAnnouncementUrl()))
            && (this.getCreattime() == null ? other.getCreattime() == null : this.getCreattime().equals(other.getCreattime()))
            && (this.getReleasetime() == null ? other.getReleasetime() == null : this.getReleasetime().equals(other.getReleasetime()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getReleaseStatus() == null ? other.getReleaseStatus() == null : this.getReleaseStatus().equals(other.getReleaseStatus()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAnnouncementId() == null) ? 0 : getAnnouncementId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAnnouncement() == null) ? 0 : getAnnouncement().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getAnnouncementUrl() == null) ? 0 : getAnnouncementUrl().hashCode());
        result = prime * result + ((getCreattime() == null) ? 0 : getCreattime().hashCode());
        result = prime * result + ((getReleasetime() == null) ? 0 : getReleasetime().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getReleaseStatus() == null) ? 0 : getReleaseStatus().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        return result;
    }
}