package com.example.order.entity;

import lombok.*;

import java.io.Serializable;
import java.util.Date;

@Data
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class GSysJournalism implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.JOURNALISM_ID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private Long journalismId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.USER_ID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.JOURNALISM
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private String journalism;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.REMARK
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.JOURNALISM_URL
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private String journalismUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.CREATTIME
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.RELEASETIME
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private Date releasetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.SORT
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private Long sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.JOURNALISM_STATUS
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private String journalismStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_journalism.IS_VALID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.JOURNALISM_ID
     *
     * @return the value of g_sys_journalism.JOURNALISM_ID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public Long getJournalismId() {
        return journalismId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.JOURNALISM_ID
     *
     * @param journalismId the value for g_sys_journalism.JOURNALISM_ID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setJournalismId(Long journalismId) {
        this.journalismId = journalismId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.USER_ID
     *
     * @return the value of g_sys_journalism.USER_ID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.USER_ID
     *
     * @param userId the value for g_sys_journalism.USER_ID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.JOURNALISM
     *
     * @return the value of g_sys_journalism.JOURNALISM
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public String getJournalism() {
        return journalism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.JOURNALISM
     *
     * @param journalism the value for g_sys_journalism.JOURNALISM
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setJournalism(String journalism) {
        this.journalism = journalism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.REMARK
     *
     * @return the value of g_sys_journalism.REMARK
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.REMARK
     *
     * @param remark the value for g_sys_journalism.REMARK
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.JOURNALISM_URL
     *
     * @return the value of g_sys_journalism.JOURNALISM_URL
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public String getJournalismUrl() {
        return journalismUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.JOURNALISM_URL
     *
     * @param journalismUrl the value for g_sys_journalism.JOURNALISM_URL
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setJournalismUrl(String journalismUrl) {
        this.journalismUrl = journalismUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.CREATTIME
     *
     * @return the value of g_sys_journalism.CREATTIME
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.CREATTIME
     *
     * @param creattime the value for g_sys_journalism.CREATTIME
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.RELEASETIME
     *
     * @return the value of g_sys_journalism.RELEASETIME
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public Date getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.RELEASETIME
     *
     * @param releasetime the value for g_sys_journalism.RELEASETIME
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.SORT
     *
     * @return the value of g_sys_journalism.SORT
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.SORT
     *
     * @param sort the value for g_sys_journalism.SORT
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.JOURNALISM_STATUS
     *
     * @return the value of g_sys_journalism.JOURNALISM_STATUS
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public String getJournalismStatus() {
        return journalismStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.JOURNALISM_STATUS
     *
     * @param journalismStatus the value for g_sys_journalism.JOURNALISM_STATUS
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setJournalismStatus(String journalismStatus) {
        this.journalismStatus = journalismStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_journalism.IS_VALID
     *
     * @return the value of g_sys_journalism.IS_VALID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_journalism.IS_VALID
     *
     * @param isValid the value for g_sys_journalism.IS_VALID
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", journalismId=").append(journalismId);
        sb.append(", userId=").append(userId);
        sb.append(", journalism=").append(journalism);
        sb.append(", remark=").append(remark);
        sb.append(", journalismUrl=").append(journalismUrl);
        sb.append(", creattime=").append(creattime);
        sb.append(", releasetime=").append(releasetime);
        sb.append(", sort=").append(sort);
        sb.append(", journalismStatus=").append(journalismStatus);
        sb.append(", isValid=").append(isValid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GSysJournalism other = (GSysJournalism) that;
        return (this.getJournalismId() == null ? other.getJournalismId() == null : this.getJournalismId().equals(other.getJournalismId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getJournalism() == null ? other.getJournalism() == null : this.getJournalism().equals(other.getJournalism()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getJournalismUrl() == null ? other.getJournalismUrl() == null : this.getJournalismUrl().equals(other.getJournalismUrl()))
            && (this.getCreattime() == null ? other.getCreattime() == null : this.getCreattime().equals(other.getCreattime()))
            && (this.getReleasetime() == null ? other.getReleasetime() == null : this.getReleasetime().equals(other.getReleasetime()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getJournalismStatus() == null ? other.getJournalismStatus() == null : this.getJournalismStatus().equals(other.getJournalismStatus()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getJournalismId() == null) ? 0 : getJournalismId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getJournalism() == null) ? 0 : getJournalism().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getJournalismUrl() == null) ? 0 : getJournalismUrl().hashCode());
        result = prime * result + ((getCreattime() == null) ? 0 : getCreattime().hashCode());
        result = prime * result + ((getReleasetime() == null) ? 0 : getReleasetime().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getJournalismStatus() == null) ? 0 : getJournalismStatus().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        return result;
    }
}