package com.example.order.entity;

import java.io.Serializable;
import java.util.Date;

public class GSysEvaluate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_evaluate.EVALUATE_ID
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    private Long evaluateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_evaluate.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_evaluate.ATTITUDE
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    private String attitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_evaluate.EFFICIENCY
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    private String efficiency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_evaluate.METER
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    private String meter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_evaluate.CREATE_TIME
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_evaluate.EVALUATE_ID
     *
     * @return the value of g_sys_evaluate.EVALUATE_ID
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public Long getEvaluateId() {
        return evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_evaluate.EVALUATE_ID
     *
     * @param evaluateId the value for g_sys_evaluate.EVALUATE_ID
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public void setEvaluateId(Long evaluateId) {
        this.evaluateId = evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_evaluate.ORDER_ID
     *
     * @return the value of g_sys_evaluate.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_evaluate.ORDER_ID
     *
     * @param orderId the value for g_sys_evaluate.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_evaluate.ATTITUDE
     *
     * @return the value of g_sys_evaluate.ATTITUDE
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public String getAttitude() {
        return attitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_evaluate.ATTITUDE
     *
     * @param attitude the value for g_sys_evaluate.ATTITUDE
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public void setAttitude(String attitude) {
        this.attitude = attitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_evaluate.EFFICIENCY
     *
     * @return the value of g_sys_evaluate.EFFICIENCY
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public String getEfficiency() {
        return efficiency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_evaluate.EFFICIENCY
     *
     * @param efficiency the value for g_sys_evaluate.EFFICIENCY
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public void setEfficiency(String efficiency) {
        this.efficiency = efficiency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_evaluate.METER
     *
     * @return the value of g_sys_evaluate.METER
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public String getMeter() {
        return meter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_evaluate.METER
     *
     * @param meter the value for g_sys_evaluate.METER
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public void setMeter(String meter) {
        this.meter = meter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_evaluate.CREATE_TIME
     *
     * @return the value of g_sys_evaluate.CREATE_TIME
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_evaluate.CREATE_TIME
     *
     * @param createTime the value for g_sys_evaluate.CREATE_TIME
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", evaluateId=").append(evaluateId);
        sb.append(", orderId=").append(orderId);
        sb.append(", attitude=").append(attitude);
        sb.append(", efficiency=").append(efficiency);
        sb.append(", meter=").append(meter);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GSysEvaluate other = (GSysEvaluate) that;
        return (this.getEvaluateId() == null ? other.getEvaluateId() == null : this.getEvaluateId().equals(other.getEvaluateId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getAttitude() == null ? other.getAttitude() == null : this.getAttitude().equals(other.getAttitude()))
            && (this.getEfficiency() == null ? other.getEfficiency() == null : this.getEfficiency().equals(other.getEfficiency()))
            && (this.getMeter() == null ? other.getMeter() == null : this.getMeter().equals(other.getMeter()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEvaluateId() == null) ? 0 : getEvaluateId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getAttitude() == null) ? 0 : getAttitude().hashCode());
        result = prime * result + ((getEfficiency() == null) ? 0 : getEfficiency().hashCode());
        result = prime * result + ((getMeter() == null) ? 0 : getMeter().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}