package com.example.order.entity;

import java.io.Serializable;

public class GSysOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.ORDER_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.OPEN_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private Long openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.CONSUMER_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private Long consumerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.FAULT_TYPE
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private String faultType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.PROBLEM
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private String problem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.FEEDBACKSRC
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private String feedbacksrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.TELEPHONE
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.COMPANY_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.ADDRESS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.CONTACT_ADDR
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private String contactAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.ORDER_STATUS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_order.SEND_SMS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private String sendSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.ORDER_ID
     *
     * @return the value of g_sys_order.ORDER_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.ORDER_ID
     *
     * @param orderId the value for g_sys_order.ORDER_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.OPEN_ID
     *
     * @return the value of g_sys_order.OPEN_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public Long getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.OPEN_ID
     *
     * @param openId the value for g_sys_order.OPEN_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setOpenId(Long openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.CONSUMER_ID
     *
     * @return the value of g_sys_order.CONSUMER_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public Long getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.CONSUMER_ID
     *
     * @param consumerId the value for g_sys_order.CONSUMER_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setConsumerId(Long consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.FAULT_TYPE
     *
     * @return the value of g_sys_order.FAULT_TYPE
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public String getFaultType() {
        return faultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.FAULT_TYPE
     *
     * @param faultType the value for g_sys_order.FAULT_TYPE
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setFaultType(String faultType) {
        this.faultType = faultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.PROBLEM
     *
     * @return the value of g_sys_order.PROBLEM
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.PROBLEM
     *
     * @param problem the value for g_sys_order.PROBLEM
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setProblem(String problem) {
        this.problem = problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.FEEDBACKSRC
     *
     * @return the value of g_sys_order.FEEDBACKSRC
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public String getFeedbacksrc() {
        return feedbacksrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.FEEDBACKSRC
     *
     * @param feedbacksrc the value for g_sys_order.FEEDBACKSRC
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setFeedbacksrc(String feedbacksrc) {
        this.feedbacksrc = feedbacksrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.TELEPHONE
     *
     * @return the value of g_sys_order.TELEPHONE
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.TELEPHONE
     *
     * @param telephone the value for g_sys_order.TELEPHONE
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.COMPANY_ID
     *
     * @return the value of g_sys_order.COMPANY_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.COMPANY_ID
     *
     * @param companyId the value for g_sys_order.COMPANY_ID
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.ADDRESS
     *
     * @return the value of g_sys_order.ADDRESS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.ADDRESS
     *
     * @param address the value for g_sys_order.ADDRESS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.CONTACT_ADDR
     *
     * @return the value of g_sys_order.CONTACT_ADDR
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public String getContactAddr() {
        return contactAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.CONTACT_ADDR
     *
     * @param contactAddr the value for g_sys_order.CONTACT_ADDR
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setContactAddr(String contactAddr) {
        this.contactAddr = contactAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.ORDER_STATUS
     *
     * @return the value of g_sys_order.ORDER_STATUS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.ORDER_STATUS
     *
     * @param orderStatus the value for g_sys_order.ORDER_STATUS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_order.SEND_SMS
     *
     * @return the value of g_sys_order.SEND_SMS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public String getSendSms() {
        return sendSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_order.SEND_SMS
     *
     * @param sendSms the value for g_sys_order.SEND_SMS
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    public void setSendSms(String sendSms) {
        this.sendSms = sendSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", openId=").append(openId);
        sb.append(", consumerId=").append(consumerId);
        sb.append(", faultType=").append(faultType);
        sb.append(", problem=").append(problem);
        sb.append(", feedbacksrc=").append(feedbacksrc);
        sb.append(", telephone=").append(telephone);
        sb.append(", companyId=").append(companyId);
        sb.append(", address=").append(address);
        sb.append(", contactAddr=").append(contactAddr);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", sendSms=").append(sendSms);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GSysOrder other = (GSysOrder) that;
        return (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
            && (this.getConsumerId() == null ? other.getConsumerId() == null : this.getConsumerId().equals(other.getConsumerId()))
            && (this.getFaultType() == null ? other.getFaultType() == null : this.getFaultType().equals(other.getFaultType()))
            && (this.getProblem() == null ? other.getProblem() == null : this.getProblem().equals(other.getProblem()))
            && (this.getFeedbacksrc() == null ? other.getFeedbacksrc() == null : this.getFeedbacksrc().equals(other.getFeedbacksrc()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getContactAddr() == null ? other.getContactAddr() == null : this.getContactAddr().equals(other.getContactAddr()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()))
            && (this.getSendSms() == null ? other.getSendSms() == null : this.getSendSms().equals(other.getSendSms()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getConsumerId() == null) ? 0 : getConsumerId().hashCode());
        result = prime * result + ((getFaultType() == null) ? 0 : getFaultType().hashCode());
        result = prime * result + ((getProblem() == null) ? 0 : getProblem().hashCode());
        result = prime * result + ((getFeedbacksrc() == null) ? 0 : getFeedbacksrc().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getContactAddr() == null) ? 0 : getContactAddr().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        result = prime * result + ((getSendSms() == null) ? 0 : getSendSms().hashCode());
        return result;
    }
}