package com.example.order.mapper;

import com.example.order.entity.GSysEvaluate;

public interface GSysEvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    int deleteByPrimaryKey(Long evaluateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    int insert(GSysEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    int insertSelective(GSysEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    GSysEvaluate selectByPrimaryKey(Long evaluateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    int updateByPrimaryKeySelective(GSysEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_evaluate
     *
     * @mbg.generated Thu Sep 24 15:08:23 CST 2020
     */
    int updateByPrimaryKey(GSysEvaluate record);
}