package com.example.order.mapper;

import com.example.order.entity.GSysAnnouncementManagement;

import java.util.List;

public interface GSysAnnouncementManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    int deleteByPrimaryKey(Long announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    int insert(GSysAnnouncementManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    int insertSelective(GSysAnnouncementManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    int updateByPrimaryKeySelective(GSysAnnouncementManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_announcement_management
     *
     * @mbg.generated Wed Sep 09 10:02:22 CST 2020
     */
    int updateByPrimaryKey(GSysAnnouncementManagement record);

    List<GSysAnnouncementManagement> getAnnouncementInfo(Long announcementId);
}