package com.example.order.mapper;

import com.example.order.entity.GSysOrderProgress;

public interface GSysOrderProgressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    int deleteByPrimaryKey(Long progressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    int insert(GSysOrderProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    int insertSelective(GSysOrderProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    GSysOrderProgress selectByPrimaryKey(Long progressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    int updateByPrimaryKeySelective(GSysOrderProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order_progress
     *
     * @mbg.generated Fri Sep 25 09:38:11 CST 2020
     */
    int updateByPrimaryKey(GSysOrderProgress record);
}