package com.example.order.mapper;

import com.example.order.entity.GSysOrder;

public interface GSysOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    int insert(GSysOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    int insertSelective(GSysOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    GSysOrder selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    int updateByPrimaryKeySelective(GSysOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_order
     *
     * @mbg.generated Wed Sep 23 16:35:23 CST 2020
     */
    int updateByPrimaryKey(GSysOrder record);
}