package com.example.order.mapper;

import com.example.order.entity.GSysJournalism;

import java.util.List;

public interface GSysJournalismMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    int deleteByPrimaryKey(Long journalismId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    int insert(GSysJournalism record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    int insertSelective(GSysJournalism record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    int updateByPrimaryKeySelective(GSysJournalism record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_journalism
     *
     * @mbg.generated Wed Sep 09 15:06:59 CST 2020
     */
    int updateByPrimaryKey(GSysJournalism record);

    List<GSysJournalism> getNewsList(long id);
}